### ISSUE TITLE
后续会开源结构搜索代码吗

### ISSUE THREAD

**Issue by jie311** [tinyvision/DAMO-YOLO#1]

**Comment by xiuyu-sxy** [comment]
结构搜索的代码是基于开源项目 https://github.com/alibaba/lightweight-neural-architecture-search 项目，demo访问地址在 https://modelscope.cn/studios/damo/TinyNAS/summary 

后续我们会更新针对DAMO-YOLO的结构搜索教程

**Comment by shituo123456** [comment]
> 

期待

**Comment by cwhgn** [comment]
适用于DAMO-YOLO的MAE-NAS教程已经更新在“Quick Start -> Customize tinynas backbone”中，具体链接如下：https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/scripts/damo-yolo/Tutorial_NAS_for_DAMO-YOLO_cn.md。欢迎试用～
