### ISSUE TITLE
如何开启矩形（rect）训练

### ISSUE THREAD

**Issue by Nirvana93** [tinyvision/DAMO-YOLO#100]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

我训练时的输入图像尺寸为1024*128，请问如何通过修改配置文件或代码来实现rect矩形框训练？

**Comment by XianzheXu** [comment]
当前版本的代码在训练和测试时只支持方形。

目前代码的默认逻辑是，不管输入图像是矩形还是方形，训练时dataloader会将图像resize成方形，再送入训练。在测试时，会自动将输入的图像resize成方形送入模型进行测试。注意，我们在resize时并不保证图像长宽比不变(根据我们的在visdrone和coco上的经验，这样效果更好)。

您可以先尝试默认设置训练，如果精度达不到预期，希望您再反馈给我们，我们安排时间做进一步的代码更新。

**Comment by Nirvana93** [comment]
好的 感谢您的回复 我们来实验测试一下
