### ISSUE TITLE
Plan to support TensorRT-INT8 (PTQ/QAT)

### ISSUE THREAD

**Issue by songkq** [tinyvision/DAMO-YOLO#12]

**Comment by jyqi** [comment]
We do have plans to support TensorRT-INT8, this feature will be released soon.

**Comment by songkq** [comment]
@jyqi Do you have a plan to release a Benchmark of MMYOLO-INT8 performance and accuracy with TensorRT PTQ/QAT?
In my practice, YOLOX-INT8 has a sharp accuracy drop (about 10% mAP) in TensorRT PTQ. Could you please provide a Tutorial to show how to debug accuracy for TensorRT-INT8 model?

**Comment by jyqi** [comment]
Thanks for your advice, we do have a plan to release a Benchmark of DAMO-YOLO-INT8 performance and accuracy. And we will release the tutorial along with the TensorRT-INT8 feature.
