### ISSUE TITLE
实时视频检测

### ISSUE THREAD

**Issue by with-him777** [tinyvision/DAMO-YOLO#15]
我看inference可以推理单张图片，可以实现实时视频检测吗，像yolov5的detect.py一样

**Comment by cwhgn** [comment]
感谢，这是个非常好的建议，我们会尽量在下一个版本中加入进来。

**Comment by XianzheXu** [comment]
@with-him777 Hello, DAMO-YOLO现已支持实时视频检测，欢迎试用。
