### ISSUE TITLE
代码可能有些路径上的bug（windows端）

### ISSUE THREAD

**Issue by athrunsunny** [tinyvision/DAMO-YOLO#16]
比如self.read_structure(
            './damo/base_models/backbones/nas_backbones/tinynas_L20_k1kx.txt')
中，需要将该路径改成绝对路径才不会报错，还有部分别的引用相对路径的地方同样会出现文件找不到的问题

**Comment by cwhgn** [comment]
非常感谢指出这个问题！目前我们的版本主要是支持linux端，所以windows关注的相对较少，我们会在下一个版本中更新这些问题。

**Comment by HYLcool** [comment]
> 比如self.read_structure( './damo/base_models/backbones/nas_backbones/tinynas_L20_k1kx.txt') 中，需要将该路径改成绝对路径才不会报错，还有部分别的引用相对路径的地方同样会出现文件找不到的问题

您好，由于windows端无法用export命令添加环境变量，因此这里您需要将installation的最后一步`export PYTHONPATH=$PWD:$PYTHONPATH
`替换为手动添加，具体步骤为（以win10为例）：
1. 右键点击“此电脑”，选择”属性“
2. 点击“高级系统设置”，并选择“环境变量”
3. 检查用户变量（一般在上半部分）中是否存在变量名为PYTHONPATH的一项
4. 如没有：
    1. 在用户变量部分点击“新建”
    2. 在其中输入变量名：PYTHONPATH，变量值：<您的DAMO-YOLO所在路径>（如D:\Projects\DAMO-YOLO）
5. 如有：
    1. 选中PYTHONPATH环境变量，并点击”编辑“
    2. 将您的DAMO-YOLO路径添加到该环境变量中
6. 点击”确定“并关闭对话框

此时DAMO-YOLO的项目路径会添加到环境变量中，其中使用到的相对路径也能够被正确解析

**Comment by athrunsunny** [comment]
@HYLcool 谢谢，我会试试的
