### ISSUE TITLE
Distillation Enhancement

### ISSUE THREAD

**Issue by Kangzf1996** [tinyvision/DAMO-YOLO#17]
I don't find the tea config and tea ckpt, will you upload it soon?

**Comment by cwhgn** [comment]
The tea models for our distilled t/s/m are no-distilled s/m/l respectively, which have not been released yet. Thanks for the question, and we will release them in the next update. Meanwhile, you can also use the released distilled s/m as the teacher to distill t/s, which we believe can provide a better result.

**Comment by Kangzf1996** [comment]
Thank you for your work!
