### ISSUE TITLE
怎么训练VOC数据集？

### ISSUE THREAD

**Issue by xiaofeng-c** [tinyvision/DAMO-YOLO#18]
您好，请问怎么训练voc数据集？谢谢

**Comment by cwhgn** [comment]
你好，目前版本暂时不支持VOC格式的数据，你可以尝试将VOC数据集转成COCO格式，然后使用我们的训练代码。后续我们会开发DAMO-YOLO对VOC格式数据的支持。感谢建议！

**Comment by xiaofeng-c** [comment]
好的，谢谢！
