### ISSUE TITLE
Questions about the model

### ISSUE THREAD

**Issue by M15-3080** [tinyvision/DAMO-YOLO#19]
When will the 1280 size model be available?

**Comment by cwhgn** [comment]
Hi, i do not get the meaning of 1280 size model? Do you mean a model trained with 1280*1280 size images?

**Comment by M15-3080** [comment]
> 嗨，我不明白 1280 尺寸模型的含义？您的意思是用 1280*1280 尺寸的图像训练的模型吗？

是的，请问什么时候会推出？

**Comment by cwhgn** [comment]
我们目前主要提供标准的640*640尺寸训练的模型，方便大家复现，并和其他工作进行公平直观的比较。针对其他各种尺寸的模型暂时没有额外的计划。如果您对特定尺寸有需求（比如1280*1280），您可以使用我们的训练教程进行相应的训练，或者使用我们640*640的模型作为初始化进行finetune。
