### ISSUE TITLE
训练coco数据集时报错，RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by funnymean** [tinyvision/DAMO-YOLO#20]
如题，按照文档操作，到训练coco数据集这一个步骤时报错如下：
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by cwhgn** [comment]
看报错可能是cuda安装问题，导致cuda不可用。可以对应显卡看下是不是cuda版本问题。

**Comment by funnymean** [comment]
> 看报错可能是cuda安装问题，导致cuda不可用。可以对应显卡看下是不是cuda版本问题。

感谢解答！ 由于我是单卡训练，后来尝试调小了batch size=16，又成功了跑起来了。这个问题无法复现。
