### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by arkerman** [tinyvision/DAMO-YOLO#3]
哈喽各位，我想请问下怎么去训练自己的数据集，coco格式的或者yolo格式的

**Comment by cwhgn** [comment]
您好，您可以将自定义数据集转成coco格式，然后使用Readme的Quick Start中“Finetune on your data”里提供的命令进行自定义数据集的训练。

**Comment by arkerman** [comment]
@cwhgn 哈喽，请问这个requirements.txt里面的所依赖的库有具体的版本要求吗？

**Comment by arkerman** [comment]
@cwhgn 哈喽这个支持单卡训练吗？我一直在报关于distributed的错

**Comment by arkerman** [comment]
@cwhgn 他一直报这个错误，是哪里出问题了吗
2022-11-30 10:10:14.802 | ERROR    | __main__:<module>:68 - An error has been caught in function '<module>', process 'MainProcess' (25404), thread 'M
ainThread' (8124):
Traceback (most recent call last):

> File "tools\train.py", line 68, in <module>
    main()
    └ <function main at 0x00000253ED19A318>

  File "tools\train.py", line 53, in main
    torch.distributed.init_process_group(backend='gloo', init_method='env://')
    │     │           └ <function init_process_group at 0x00000253EC862DC8>
    │     └ <module 'torch.distributed' from 'D:\\Anaconda3\\envs\\DAMO-YOLO\\lib\\site-packages\\torch\\distributed\\__init__.py'>
    └ <module 'torch' from 'D:\\Anaconda3\\envs\\DAMO-YOLO\\lib\\site-packages\\torch\\__init__.py'>

  File "D:\Anaconda3\envs\DAMO-YOLO\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
    │            │     │                   └ datetime.timedelta(seconds=1800)
    │            │     └ -1
    │            └ -1
    └ 'env://'

  File "D:\Anaconda3\envs\DAMO-YOLO\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
                                                                │      └ <property object at 0x00000253E9FE0AE8>
                                                                └ ParseResult(scheme='env', netloc='', path='', params='', query='', fragment='')    

RuntimeError: No rendezvous handler for env://

**Comment by oziasly** [comment]
我也有这个问题，请问是不支持Windows单卡训练吗

**Comment by cwhgn** [comment]
感谢关注，我们是支持Windows单卡训练的，具体问题可以参考ISSUE #7 #16 #43 。

**Comment by oziasly** [comment]
> 感谢关注，我们是支持Windows单卡训练的，具体问题可以参考ISSUE #7 #16 #43 。

谢谢，已经找到解决方法了
