### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by v3551G** [tinyvision/DAMO-YOLO#33]
在执行这一句pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'时,总报错:
(damo-yolo) masterqkk@QKK:~/workspace/pycharm/DAMO-YOLO$ pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-lg51638m
  Running command git clone --filter=blob:none --quiet https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-lg51638m

  error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  fatal: the remote end hung up unexpectedly
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-lg51638m did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-lg51638m did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

能否帮忙看下?

**Comment by cwhgn** [comment]
It seems the error comes from the checkout in "git clone". You may add "export GIT_SSL_NO_VERIFY=1" in your ~/.bashrc to see whether it works.

**Comment by v3551G** [comment]
> It seems the error comes from the checkout in "git clone". You may add "export GIT_SSL_NO_VERIFY=1" in your ~/.bashrc to see whether it works.

谢谢,这个问题解决了
