### ISSUE TITLE
极客平台直播关于CWD的蒸馏问题

### ISSUE THREAD

**Issue by Senwang98** [tinyvision/DAMO-YOLO#34]
从极客平台直播过来的，我想确认一下是不是ppt中的teacher与student的align层搞反了？
<img width="1917" alt="f5da28e27badd8c6226db21e5b16ca8" src="https://user-images.githubusercontent.com/23122139/206450547-d6594e4c-0149-43d7-bc6c-a9960e96af5d.png">

**Comment by XianzheXu** [comment]
感谢您的提醒，确实是ppt上的框图有误，正确的流程是student的特征经过Align module向teacher对齐，而teacher特征不经过Align module，具体细节可以参考https://github.com/tinyvision/DAMO-YOLO/blob/c9c5c2af62d20c013e8c0b039ef5b21875a71825/damo/base_models/losses/distill_loss.py#L42-L47
