### ISSUE TITLE
如何训练自己的数据集？

### ISSUE THREAD

**Issue by zlszhonglongshen** [tinyvision/DAMO-YOLO#38]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

能不能给个详细训练自己数据集的教程？
另外，建议，把需要自己手动调整的参数都写在一起，现在调整都要找好几个文件，而且还找不到。

**Comment by havefunheehee** [comment]
已解决，谢谢！

**Comment by XianzheXu** [comment]
感谢您的建议，我们会在下一个版本中加入详细的使用自有数据进行训练的教程，包括数据格式转换和训练的配置修改等信息，希望您保持关注。

**Comment by zlszhonglongshen** [comment]
> 感谢您的建议，我们会在下一个版本中加入详细的使用自有数据进行训练的教程，包括数据格式转换和训练的配置修改等信息，希望您保持关注。

好的。谢谢

**Comment by cwhgn** [comment]
您好，我们针对自由数据训练教程已经放出来啦，请参考https://github.com/tinyvision/DAMO-YOLO/blob/master/assets/CustomDatasetTutorial.md

**Comment by zlszhonglongshen** [comment]
> 您好，我们针对自由数据训练教程已经放出来啦，请参考https://github.com/tinyvision/DAMO-YOLO/blob/master/assets/CustomDatasetTutorial.md
已经完成模型训练，好用
