### ISSUE TITLE
loss一直都是0

### ISSUE THREAD

**Issue by liumingzhu6060** [tinyvision/DAMO-YOLO#39]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

训练自己的数据集，loss一直为0，请问是什么原因，需要在哪里改label的类别吗？
![image](https://user-images.githubusercontent.com/79501943/206661361-c0c75f7b-d432-4bea-bf00-2dc951b843ac.png)

**Comment by yutao007** [comment]
是的，训练代码确实有问题，你需要关掉augment。可以选择self.train.no_aug_epochs = 300，但是这样训练的map就会差很多。

**Comment by XianzheXu** [comment]
您好，能麻烦分享一下您在finetune时候的参数改动吗？我们尝试复现一下这个问题并进行修复。

**Comment by yutao007** [comment]
谢谢您的回复，我训练自己的5类数据集。只有在config.yaml中设置self.train.no_aug_epochs = 300（关掉数据导入时的augment）且不带预训练模型才能正常的跑起来，但是这样训练的map就会比同期我使用yolov5,v6,v7差很多。当我选择带预训练模型的finetune时就会报5类与80类不符合的冲突，作者代码中应该没有冻结预训练模型最后一层的参数导入。
最后如果作者想要复现问题，按照自己给的readme，做一个不是80类的数据集跑一下就明了。

**Comment by qiqika** [comment]
@liumingzhu6060 
you can add code segments=[] before line if (n and segments is None ) in function random_affine() of mosaic_wrapper.py . I think the segments is none make the target label empty

**Comment by XianzheXu** [comment]
@liumingzhu6060 我们更新了代码，并且增加了使用自有数据进行finetune训练的教程，您可以参考该教程再试试。有任何问题可以继续在这个issues下留言，我们保持密切关注。
