### ISSUE TITLE
关于DAMO-YOLO的模型速度

### ISSUE THREAD

**Issue by khwengXU** [tinyvision/DAMO-YOLO#44]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

DAMO-YOLO是很棒的工作！
我观察到 DAMO-YOLO 的速度评测是按照 Batch Size = 1 进行评估的，想询问下这边有试过更多batch size的速度比较吗（比如 Batch Size = 32的情况）

**Comment by jyqi** [comment]
您好，感谢您对DAMO-YOLO的关注，我们有试过更多batch size的速度比较，如DAMO-YOLO-S在batch size=32，T4GPU下，TRT Latency为3.05ms。
