### ISSUE TITLE
关于AlignOTA

### ISSUE THREAD

**Issue by GreatZeZuo** [tinyvision/DAMO-YOLO#45]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

assigner中的代码貌似和文章中写的操作不一致，请问这是什么原因（也可能是我理解错了）：比如在计算回归cost时，代码用的负log iou，而文章中是取负 iou；scale_factor的计算时，使用的是abs().pow(2.0)，而不是绝对值。

**Comment by XianzheXu** [comment]
感谢您的关注，您的理解是正确的。在alignOTA中， reg_cost = - ln(iou).  scale_factor = |IoU-cls_(pred)|^2。paper和code的差异是因为更新周期不同导致paper和code不同步，我们也正在更新arxiv上的paper，让paper和code保持一致。

**Comment by GreatZeZuo** [comment]
感谢回复，借此顺便想问一下这样修改的原理是什么呢？文章在这边部分的解释没有太明白。如果可以，您可以解释一下原理吗，十分感谢！

**Comment by zero0kiriyu** [comment]
现在的AlignOTA和Nanodet Plus的dsl区别在哪里？

**Comment by XianzheXu** [comment]
> 感谢回复，借此顺便想问一下这样修改的原理是什么呢？文章在这边部分的解释没有太明白。如果可以，您可以解释一下原理吗，十分感谢！

@GreatZeZuo  将reg_cost变成-ln(iou)是因为cls_cost的focal loss也是对数形式，经过这样的修改可以使两者在曲线形式上对齐，scale_factor变成平方是经过调参发现focal loss的gamma参数调整为2比1效果好，经过我们实验验证，这两点修改后，相比于paper中描述的alignOTA，在DAMO-YOLO-S上能提升1.1的mAP。

**Comment by XianzheXu** [comment]
> 

@zero0kiriyu  感谢您的提醒，经过我们的对比和分析，经过改进后的alignOTA和dsl assigner在cost计算上非常类似。但是在grid point的过滤上有较大差别。
