### ISSUE TITLE
Customize tinynas backbone tutorial dont work with customize parameters 

### ISSUE THREAD

**Issue by qiqika** [tinyvision/DAMO-YOLO#47]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

As Customize tinynas backbone tutorial, it needs like the conv_data.out.fp16.damoyolo file, how to get the customize file if change parameters?

**Comment by HYLcool** [comment]
Hi @qiqika, thanks for your attention~

In the update of LightNAS last month, this latency database file conv_data.out.fp16.damoyolo had been added [here](https://github.com/alibaba/lightweight-neural-architecture-search/tree/main/latency/op_profiler/V100). Perhaps you pulled the repo before this update.

You can pull the [latest version of the main branch in LightNAS](https://github.com/alibaba/lightweight-neural-architecture-search/tree/main) and try again. And please get in touch with us if you have any further issues.
