### ISSUE TITLE
关于GiraffeNeckV2 Fusion block个数的问题

### ISSUE THREAD

**Issue by handsomelada** [tinyvision/DAMO-YOLO#49]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

作者你好，有一个问题。在GiraffeNeckV2代码中只看到了5个Fusion Block，也就是对应的self.merge_x （x=3,4,5,6,7），那么对应论文里的最大特征图分支的最后一个Fusion Block在哪？以及self.merge_7的来自最大特征图分支的输入也没有在代码里看到
![微信图片_20221220111150](https://user-images.githubusercontent.com/52120378/208573081-79e4b260-aaf8-4fd5-962d-8e2d228687c2.jpg)

**Comment by jyqi** [comment]
您好，感谢您对DAMOYOLO工作的关注。抱歉这张图给您带来了误解，由于考虑到node 7只接受一个入度(即node 5)的输入，我们验证了1) 使用Fusion Block进行特征变换和2) 直接将node 5赋值为node 7两种方式的模型精度，发现精度差异很小，因此为了加速模型时间，我们采用第二种方案，但是图没有进行相应的更新，我们会在下一版本的文章内更新Neck图。再次抱歉给您带来了困扰。
