### ISSUE TITLE
Question：没有cpu版本的吗

### ISSUE THREAD

**Issue by simple123456T** [tinyvision/DAMO-YOLO#50]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

只能在有gpu的机器上运行吗，纯cpu机器不能运行吗

**Comment by jyqi** [comment]
您好，我们是支持cpu上的推理。推理时我们会判断gpu是否可用，若gpu不可用，则自动选择cpu进行模型推理，您不需要显示指定运行设备。
