### ISSUE TITLE
[Bug]: 虚拟环境安装cocoapi包

### ISSUE THREAD

**Issue by simple123456T** [tinyvision/DAMO-YOLO#51]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

Windows10

### Device

cpu

### Python version

3.8

### PyTorch version

1.7

### torchvision version

0.8

### Describe the bug

Windows 
conda虚拟环境
安装cocoapi报错
正确安装命令如下：
pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

亲测有效，望采纳

### To Reproduce

安装包命令错误，详细见上。

**Comment by jyqi** [comment]
您好，感谢您对DAMO-YOLO的关注，我们实测您给的安装命令在Windows是有效的，感谢建议，我们将在README上进行更新。
