### ISSUE TITLE
Can upload model files in releases?

### ISSUE THREAD

**Issue by khursani8** [tinyvision/DAMO-YOLO#52]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Download speed so slow
![Screenshot from 2022-12-20 20-46-23](https://user-images.githubusercontent.com/5404903/208670809-a88c999c-f8db-4727-aac0-790dc6a07e2b.png)

Can you upload it in https://github.com/tinyvision/DAMO-YOLO/releases

**Comment by XianzheXu** [comment]
Thanks for your attention, we will add the download link in Google Cloud later。
