### ISSUE TITLE
RepGFPN结构，代码中的实现和论文的图片不一致问题

### ISSUE THREAD

**Issue by yang-0201** [tinyvision/DAMO-YOLO#53]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

我仔细看了代码中的Efficient RepGFPN的实现过程，发现实际代码与论文里的图片有挺大的出入，比如代码中一共是5个merge CSPstage模块，而论文中是6个，是为了图片更为工整嘛，比如从主干最后一层按顺序进行的话第三个CSPstage模块就已经用于输出了，而在图中是第四个模块才用于输出

**Comment by yang-0201** [comment]
又仔细想了下，是因为论文中说到的额外的上采样操作导致延迟下降，精度提升不大的原因，为了权衡所以去掉了一个模块嘛

**Comment by HYLcool** [comment]
duplicate with this existing issue: https://github.com/tinyvision/DAMO-YOLO/issues/49#issue-1503922258
