### ISSUE TITLE
训练自己的数据集整体损失值不降反增，但测试的时候又可以正常检测到目标

### ISSUE THREAD

**Issue by Spratumn** [tinyvision/DAMO-YOLO#54]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

我在训练自己的数据集时，观测到训练过程中整体损失值不降反增，但我用训练得到的权重进行测试的时候又可以正常检测到目标，这是什么情况呢？

**Comment by HYLcool** [comment]
@Spratumn 您好，如果方便的话，您可以给我们提供一下训练log吗？
或者如果您觉得issue中交流不太方便的话，可以通过电子邮件与我们交流：lielin.hyl@alibaba-inc.com

**Comment by Spratumn** [comment]
我是把官方模型移植到自己的框架的时候有几个地方写错了，已修正没问题了。
