### ISSUE TITLE
[Bug]: Can not run the demo on RTX4090!

### ISSUE THREAD

**Issue by thinktu2** [tinyvision/DAMO-YOLO#57]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

Ubuntu

### Device

RTX4090

### CUDA version

10.2

### TensorRT version

None

### Python version

3.7

### PyTorch version

1.7.0

### torchvision version

0.8.0

### Describe the bug

When I run the demo to detect dog.jpg, a warning occurs, and the program is stuck.
```bash
/<condapath>/envs/damo-yolo/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```
I have to kill this zombie process.

### To Reproduce

Run demo command

`python tools/torch_inference.py -f configs/damoyolo_tinynasL20_T.py --ckpt weights/damoyolo_tinynasL20_T_418.pth --path assets/dog.jpg`

A warning as described above occurs, and the program is stuck.

### Additional

Actually, I have solved this problem.
Maybe cu102 is too old for RTX4090, and cu116 is suitable, I think.
1. Update the latest nvidia driver, which I have is **525.60.11**.
2. Install **pytorch** with `pip` instead of conda.
`pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116`
When I use conda, I get a `PackagesNotFoundError`, but using **pip** is work.

Run the demo command and I get the expected output, an image with 3 bbox.

**Comment by HYLcool** [comment]
@thinktu2 Hi, thanks for your attention!

What you said above is right. As this previous issue #35 showed, RTX 30xx and 40xx series GPUs from Nvidia only support CUDA 11.x. So the first solution is to upgrade your CUDA driver and cudatoolkit.

If you want to install cudatoolkit and PyTorch with conda, you can follow the official instructions from [here](https://pytorch.org/get-started/previous-versions/). You just need to make sure that the PyTorch version is what you need and the cudatoolkit version <= your CUDA driver version.

By the way, we are validating DAMO-YOLO on the later version of PyTorch and CUDA, including the latest PyTorch 2.0 and CUDA 11.x. When everything is OK, we will update the repo.

Please get in touch with us if you have any further issues.

**Comment by thinktu2** [comment]
@HYLcool Thank you for your answer! DAMO-YOLO is a meaningful work. Looking forward to the next update!
