### ISSUE TITLE
Inference on arbitrary image sizes.

### ISSUE THREAD

**Issue by trathpai** [tinyvision/DAMO-YOLO#58]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Hello,

Is there a way to infer on arbitrary image sizes , specifically higher resolutions and rectangular images?

Thanks

**Comment by XianzheXu** [comment]
Hi,

**Comment by XianzheXu** [comment]
Hi,
We update the demo tools recently, and it should work with arbitrary image sizes. Please note that the image size should be divisible by 32. Take torch inference engine as example，the usage is like below：
`python tools/demo.py -f configs/damoyolo_tinynasL25_S.py --engine ../damoyolo_tinynasL25_S.pth --engine_type torch --path ./assets/dog.jpg --infer_size 640 960
`
