### ISSUE TITLE
建议导出的onnx输出层，不管是S模型、M模型还是T模型，导出层的名称保持一致，要不然解析需要做分支

### ISSUE THREAD

**Issue by xinsuinizhuan** [tinyvision/DAMO-YOLO#60]
### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar feature requests.

### Description

T模型的onnx：
![图片](https://user-images.githubusercontent.com/40679769/210057594-94ebe71d-b2da-4647-9270-3de279d1e739.png)
S模型的onnx:
![图片](https://user-images.githubusercontent.com/40679769/210057645-93194df4-48bc-415f-aea8-c27754e1efdc.png)
Mmo模型的onnx:
![图片](https://user-images.githubusercontent.com/40679769/210057703-5b430fd2-37b3-45d1-9e0f-e6a8312767ae.png)

### Additional

不同的模型，我得重新写或者做分支区分类别来对应不同的解析，建议整成一样的。

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by cwhgn** [comment]
感谢建议，后面我们新版本中会尽量保证一致。
