### ISSUE TITLE
readme里的"Finetune on your data"是指什么？

### ISSUE THREAD

**Issue by fppccc** [tinyvision/DAMO-YOLO#62]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

您好！请问"Finetune on your data"是指训练吗？
我已经按照**[custom dataset tutorial]**
(https://github.com/tinyvision/DAMO-YOLO/blob/master/assets/CustomDatasetTutorial.md)
在自己的小数据集上尝试了，每一步都按照教程来，使用了M模型，并准备好了预训练权重。但是AP值几乎为0，这个小数据集之前在其他模型上跑过，可以确定格式没问题（coco格式）。请问我该如何解决问题呢？
非常感谢！

**Comment by cwhgn** [comment]
请问下您的数据集train和test的数据集类别和标签是一致的么？

**Comment by XianzheXu** [comment]
@fppccc 麻烦看一下您数据集的train.json和val.json中的categories字段中的类别映射排序是否一致，在当前的版本中，若train.json和val.json中的categories字段中的类别映射顺序不一样，会导致train和val时的类别映射不对齐。您可以手动将train.json和val.json中的categories字段中的类别映射顺序调整一致来避免该问题。后续我们会推出新版本修复该问题，敬请保持关注。

**Comment by HYLcool** [comment]
This issue will be closed due to inactivity. Please reopen as needed.
