### ISSUE TITLE
configs\damoyolo_tinynasL25_S.py doesn't contains class named 'Config'

### ISSUE THREAD

**Issue by Wisdom2wisdom** [tinyvision/DAMO-YOLO#64]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Traceback (most recent call last):

> File "E:/executable_code/YOLO/DAMO-YOLO-master/tools\train.py", line 85, in <module>
    main()
    └ <function main at 0x000001AAA9F07820>

  File "E:/executable_code/YOLO/DAMO-YOLO-master/tools\train.py", line 76, in main
    config = parse_config(args.config_file)
             │            │    └ 'configs\\damoyolo_tinynasL25_S.py'
             │            └ Namespace(config_file='configs\\damoyolo_tinynasL25_S.py', local_rank=0, opts=[], tea_ckpt=None, tea_config=None)
             └ <function parse_config at 0x000001AAAABA7A60>

  File "E:\executable_code\YOLO\DAMO-YOLO-master\damo\config\base.py", line 134, in parse_config
    return get_config_by_file(config_file)
           │                  └ 'configs\\damoyolo_tinynasL25_S.py'
           └ <function get_config_by_file at 0x000001AAAAB7ED30>

  File "E:\executable_code\YOLO\DAMO-YOLO-master\damo\config\base.py", line 121, in get_config_by_file
    raise ImportError(

ImportError: configs\damoyolo_tinynasL25_S.py doesn't contains class named 'Config'

**Comment by cwhgn** [comment]
hi, a solution can be found in #41 .
