### ISSUE TITLE
Will pip support be added?

### ISSUE THREAD

**Issue by kadirnar** [tinyvision/DAMO-YOLO#66]
### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar feature requests.

### Description

I am the creator and maintainer of the [yolov6](https://github.com/kadirnar/yolov6-pip) and [yolov7](https://github.com/kadirnar/yolov7-pip) pypi packages.

I am also developing the [torchyolo](https://github.com/kadirnar/torchyolo/) library. It supports Yolov5, yolov6, yolov7 and YOLOX models. I would also like to add the Damo-yolo model. Are you considering adding pip support?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by cwhgn** [comment]
We have no plans on pip support yet. But it's a great idea! If you are interested in damo-yolo pypi package, please let us know when you are ready. And we are happy to add it in our project.

**Comment by kadirnar** [comment]
Hello, I can add. But you already have the pip package. Only the helpers.py file needs to be written.

**Comment by cwhgn** [comment]
Current pip package in the project is a simple version mainly used for our offline pip install. And there is no pypi version yet. You can used it directly. And if you have any modification,  we are happy to merge it in.
