### ISSUE TITLE
Custom Data Training

### ISSUE THREAD

**Issue by junghyun-avikus** [tinyvision/DAMO-YOLO#67]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Are there any specific naming rules for custom dataset? e.g. image names are integers like COCO dataset.

It seems like MosaicWrapper has its own way to set names for training image files,
but I couldn't really find out what it does.

For example,
one of the my dataset is "26.09961_-80.11731_0.0.jpg",
and I get an error saying that path/to/my_dataset/26.jpg does not exist.

**Comment by cwhgn** [comment]
We use `torchvision.datasets.coco` to load images, as below:
https://github.com/tinyvision/DAMO-YOLO/blob/f8a5d87ddaa540ecaa24bb2c065c4a8c3665bfb0/damo/dataset/datasets/coco.py#L50
It is better to name your images without `.` to ensure your images loading smoothly.
