### ISSUE TITLE
Questions about best weights and resume options

### ISSUE THREAD

**Issue by Mariquery** [tinyvision/DAMO-YOLO#68]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Hello all,
I have a couple of questions about DAMO-YOLO. 
First, related to best weights, I have done training with my data but it does not save me the best weights.
Is this because it's not implemented yet or I need to modify something in the code?
Secondly, is there an option to relaunch a training from a specific epoch (or the last epoch processed in case of an error)?

Thanks in advice,
A greeting,
María.

**Comment by XianzheXu** [comment]
Hi, 
For the first question, During the training, we didn't save the best weights in this code yet. However, we log the validation mAP in ./workdirs/your_exp_names/train_log.txt, you can find the best weight and pick it up from saved checkpoints. 

Secondly, you can resume training by set config.training.resume_path = './workdirs/your_exp_names/epoch_xxx_ckpt.pth' in your configs.py. We update code related to this part, you may need to pull the recent commit to make the resume work.

**Comment by Oncecaddy** [comment]
Hi @XianzheXu I am trying to train with custom dataset. Bu I can't exactly figured out how to resume a training. According to what you wrote, I need to edit the configs.py folder, but there is no such python file. When I searched the other files, I saw that there was an option called 'resume_path': None in damo > configs > base.py folder on line 39 and I edited here, but it didn't help if I edited it, still the training starts from the beginning. Looking forward to your help, thanks.

**Comment by Oncecaddy** [comment]
> Hi @XianzheXu I am trying to train with custom dataset. Bu I can't exactly figured out how to resume a training. According to what you wrote, I need to edit the configs.py folder, but there is no such python file. When I searched the other files, I saw that there was an option called 'resume_path': None in damo > configs > base.py folder on line 39 and I edited here, but it didn't help if I edited it, still the training starts from the beginning. Looking forward to your help, thanks.

When I followed the code, in order to resume the training, for example, deleting the self.train.finetune_path path in the damoyolo_tinynasL20_T.py file in the configs folder and giving the resume_path option on line 39 in damo > configs > base.py as mentioned above allowed me to continue the training. I found the solution myself, thank you anyway :D.

![image](https://github.com/tinyvision/DAMO-YOLO/assets/93985400/e7347501-d2f5-4be7-93c6-5184d39483b4)
