### ISSUE TITLE
怎么用单卡训练？

### ISSUE THREAD

**Issue by xinhaojin** [tinyvision/DAMO-YOLO#7]
如题

**Comment by jyqi** [comment]
你好，将--nproc_per_node设为1即可进行单卡训练。

**Comment by arkerman** [comment]
@jyqi 你好帅哥，我已经按照你的提示设置了单卡，但是报了以下的错误：

2022-11-30 10:10:14.802 | ERROR    | __main__:<module>:68 - An error has been caught in function '<module>', process 'MainProcess' (25404), thread 'M
ainThread' (8124):
Traceback (most recent call last):

> File "tools\train.py", line 68, in <module>
    main()
    └ <function main at 0x00000253ED19A318>

  File "tools\train.py", line 53, in main
    torch.distributed.init_process_group(backend='gloo', init_method='env://')
    │     │           └ <function init_process_group at 0x00000253EC862DC8>
    │     └ <module 'torch.distributed' from 'D:\\Anaconda3\\envs\\DAMO-YOLO\\lib\\site-packages\\torch\\distributed\\__init__.py'>
    └ <module 'torch' from 'D:\\Anaconda3\\envs\\DAMO-YOLO\\lib\\site-packages\\torch\\__init__.py'>

  File "D:\Anaconda3\envs\DAMO-YOLO\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
    │            │     │                   └ datetime.timedelta(seconds=1800)
    │            │     └ -1
    │            └ -1
    └ 'env://'

  File "D:\Anaconda3\envs\DAMO-YOLO\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
                                                                │      └ <property object at 0x00000253E9FE0AE8>
                                                                └ ParseResult(scheme='env', netloc='', path='', params='', query='', fragment='')    

RuntimeError: No rendezvous handler for env://

这是啥原因呀？

**Comment by jyqi** [comment]
你好，看到你的backend改成了gloo，是因为在windows平台训练吗？我们在linux平台上尝试单卡训练，没有碰到过这个错误。可以排查下是否平台原因。

**Comment by arkerman** [comment]
@jyqi 好的，谢谢你的建议
