### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asylum127** [tinyvision/DAMO-YOLO#71]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

ubuntu

### Device

nvidia 2080ti

### CUDA version

cuda10.1

### Python version

3.7

### PyTorch version

1.7.2

### torchvision version

0.8.0

### Describe the bug

我在训练自己的数据集后，在推理时出现报错
![image](https://user-images.githubusercontent.com/112939607/215314242-9d1378c7-57f9-4fb2-9ae9-e9c96026753c.png)
数据集中标签总共有三个类，推理结果中类为“1，2，3”（cls_inds为‘1，2，3’，而非‘0，1，2）
在“visualize.py”中直接用"cls_ids"作为索引会导致报错

### To Reproduce

我将代码改为：
![image](https://user-images.githubusercontent.com/112939607/215314470-50e4d308-12a1-47ab-a1e2-82008f23fd46.png)
可以正常推理
请问这个bug是原来代码中就存在的问题，还是我训练时的出错导致的

**Comment by XianzheXu** [comment]
请问您使用的是最新的代码吗？如果不是的话麻烦您pull一下最新代码再尝试推理。如果是的话，麻烦查看一下训练和推理的config文件，其中head的num_classes是否是正确设置的？

**Comment by asylum127** [comment]
> 请问您使用的是最新的代码吗？如果不是的话麻烦您pull一下最新代码再尝试推理。如果是的话，麻烦查看一下训练和推理的config文件，其中head的num_classes是否是正确设置的？

num_classes设置为3，我的数据中有三个类的标签

**Comment by XianzheXu** [comment]
您的代码是最新的吗？我们在commit: ee8050e1621897b5ec84670a1b33b6a086a75b55中修复过此问题，麻烦再确认一下您当前代码是否包含该次commit
