### ISSUE TITLE
关于混合精度训练.

### ISSUE THREAD

**Issue by z1069614715** [tinyvision/DAMO-YOLO#74]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

DAMO-YOLO的作者你好，我想问问你们的项目不使用混合精度训练的原因？是因为混合精度有可能带来loss为nan的问题吗？

**Comment by cwhgn** [comment]
感谢建议，的确目前的版本是没有混合精度训练的。这是个很好的建议，我们后续会把它加进来。

**Comment by z1069614715** [comment]
感谢回复，期待你们的更新.
