### ISSUE TITLE
pred_score的shape是[b,8400,nc+1]还是[b,8400,nc]？

### ISSUE THREAD

**Issue by fppccc** [tinyvision/DAMO-YOLO#75]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

您好，我在调试代码的时候发现，最后的pred_score的shape是[b,8400,nc+1]，请问正常情况下是不是应该为[b,8400,nc]？这是否意味着我的数据集类别映射错误？
同时，我也发现我的数据集COCO格式的json标注中，类别从1开始，是不是从0开始就能解决这个问题？

**Comment by cwhgn** [comment]
感谢关注！nc+1中多出来的+1维是为了兼容之前版本不同的index映射，不影响正常训练的。COCO数据index从0开始是没问题的，我们在处理COCO数据时会把他重新映射的，如下代码：
https://github.com/tinyvision/DAMO-YOLO/blob/9dc625e54edf3c07474630efdbbd397dd857e168/damo/dataset/datasets/coco.py#L21-L28
