### ISSUE TITLE
在自己数据集上fine-tune，对比yolov5，damo-yolo预测的fp过多

### ISSUE THREAD

**Issue by klykq111** [tinyvision/DAMO-YOLO#77]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

作者您好，我目前尝试使用自己的数据在damo-yolo tiny上finetune。由于之前已经在yolov5s上进行过finetune，所以现在为了对比在damo-yolo上的效果，我在finetune的时候，将batch-size改为80、整个训练过程中都使用数据增强、训练30个epoch，这与我在yolov5上finetune的设定一致，其余训练超参数没有改变；测试时的conf_thre和nms_iou_thre也改为了和yolov5一致。但是最终在测试集上的结果，damo-yolo tiny的预测框会比yolov5s多很多，它们俩的预测的tp差不多，但是damo-yolo tiny预测的fp是yolov5s的7倍，导致mAP低了7个点左右。
我现在对于出现的这种情况有点困惑，不知道是什么导致了damo-yolo tiny中fp过多，是否模型还需要训练更多epoch？
如果您能有什么意见或者建议的话，我将非常感谢，期待您的回复。

**Comment by XianzheXu** [comment]
DAMO-YOLO没有objectness分支并且在nms时采用的是multiclass nms，建议将conf_thre设置的更大一些。

**Comment by klykq111** [comment]
感谢您的回复，但是我这个数据集只有一个类别，所以是不是multiclass nms应该没有影响。我看论文，damo-yolo在训练的时候，对于分类分支正负样本都会进行训练，但是从结果来看，它把很多负样本也给了挺高的置信度，导致fp过多，不清楚怎么回事。
