### ISSUE TITLE
关于AlignOTA的移植

### ISSUE THREAD

**Issue by fppccc** [tinyvision/DAMO-YOLO#78]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

您好！
我对AlignOTA的工作很感兴趣，希望能用在科研工作中，并将其移植到了其他算法中。然而随着训练的进行，AP值不断下降。我反复debug了许久，找不到错误所在，请问您有好的排除错误的建议吗？

**Comment by XianzheXu** [comment]
感谢您的关注，按照个人经验，初步调试可以可视化一下训练好的模型的分配结果，观察label assign是否合理。在label assign的代码调试过程中，很容易由于对stride和feature grid没对齐导致出错。
