### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by luhu65** [tinyvision/DAMO-YOLO#79]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

Ubuntu

### Device

3090

### CUDA version

11.1

### Python version

3.7

### PyTorch version

1.10.0

### torchvision version

0.110

### Describe the bug

在自己数据集上，可以运行T模型，运行S和M模型在训练时 验证map值时报错。
![image](https://user-images.githubusercontent.com/82073527/218291215-79b1dc8f-d9ee-4ef1-bafe-ac74720c07bb.png)

### To Reproduce

 CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port 29501 tools/train.py -f configs/damoyolo_tinynasL25_S.py

**Comment by luhu65** [comment]
运行eval.py报错
![image](https://user-images.githubusercontent.com/82073527/218293066-e7b16420-0087-4398-9a41-b09153f8883e.png)

**Comment by cwhgn** [comment]
看报错信息貌似是标注文件中annotation里的标签并没有在categories字段中定义，您可以先check下数据，有问题我们再随时沟通。

**Comment by luhu65** [comment]
> 看报错信息貌似是标注文件中annotation里的标签并没有在categories字段中定义，您可以先check下数据，有问题我们再随时沟通。

谢谢回复！我可以运行DAMO-T ,但当运行DAMO-S和DAMO-M 在验证mAP时报错。

**Comment by luhu65** [comment]
更奇怪的是，我训练了damo-S 300个epoch，有epoch_290_ckpt.pth可以验证, 其他epoch.pth 都不行 是不是其他权重文件mAP值太低了

**Comment by cwhgn** [comment]
方便贴下报错信息截图么？

**Comment by luhu65** [comment]
> 方便贴下报错信息截图么？

十分感谢您的回复，还是和之前一样的错误，模型在验证集上进行验证，计算mAP（coco）是报错，详细截图如下。
![image](https://user-images.githubusercontent.com/82073527/218635247-7f7de5b9-71d3-44e2-ae5f-146c6909efb2.png)
有意思的是当我训练damo-s模型是，每10个epoch保存一次模型权重文件，当我利用tools/eval.py 对 epoch_290_ckpt.pth进行验证，就没有报错，其他epoch_*_ckpt.pth就会有像截图所示的报错，我个人对这个bug的理解是有些模型权重文件在我自己数据集上推理出的结果太差了，导致无法计算mAP值。

**Comment by cwhgn** [comment]
看了下您的问题，貌似是config中self.dataset.class_names没有设置的问题，您可以check下。

**Comment by luhu65** [comment]
> 看了下您的问题，貌似是config中self.dataset.class_names没有设置正确的问题，您可以check下。同时，也可以check下Zerohead的num_classes是否设置正确。

感谢解答，ZeroHead的num_classes 没有修改成自己数据集的类别数，问题已解决！
