### ISSUE TITLE
Why is the mAP of this yolo only excellent on S and T, but not very high on M? 

### ISSUE THREAD

**Issue by floveqq** [tinyvision/DAMO-YOLO#8]
When not apply distillation.
Is it not suitable for large models ?

**Comment by jyqi** [comment]
Our main motivation is to achieve a faster and more accurate object detection. Therefore, many of our techs pay more attention on the smaller-size models, such as Efficient RepGFPN and ZeroHead, which provides a higher improvement on the smaller-size models than that on the larger-size models.

**Comment by floveqq** [comment]
So will you design other strategies for the large yolo model？

**Comment by jyqi** [comment]
Yes, there  will be other network design strategy for our L/X model. We will release them soon.
