### ISSUE TITLE
How can I export this model to TensorFlow Lite format and compile it for Edge TPU?

### ISSUE THREAD

**Issue by EdjeElectronics** [tinyvision/DAMO-YOLO#80]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Hello, I would like to try exporting DAMO-YOLO to TensorFlow Lite format (`.tflite`). I want to try running this model on a Coral USB Accelerator, which also requires compiling the TFLite model to EdgeTPU format. Are there any instructions I can follow? Has anyone else tried this? 

The Ultralytics YOLOv5 repository makes it easy to [convert a model to TFLite and compile it for Edge TPU](https://github.com/ultralytics/yolov5/releases/tag/v6.1). Does DAMO-YOLO have a similar feature?

### Additional

Thanks for your great work on this repository!

**Comment by cwhgn** [comment]
Currently we do not support converting DAMO-YOLO to tflite. You may try some public tools to solve this problem, for example [TFLite Conversion](https://github.com/sithu31296/PyTorch-ONNX-TFLite). Thanks for your question. We will add this into our next plan.
