### ISSUE TITLE
[Bug]: IndexError: Dimension out of range when running demo.py with TensorRT file

### ISSUE THREAD

**Issue by YangXJ95** [tinyvision/DAMO-YOLO#81]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

Ubuntu20.04

### Device

Nvidia RTX3070 

### Python version

3.7

### PyTorch version

1.7.0

### torchvision version

0.8.1

### Describe the bug

Followed the instruction to convert the provided .pth file to .trt file:
`python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval`
and ran the trt inference:
`python tools/demo.py -f ./configs/damoyolo_tinynasL25_S.py --engine ./deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --engine_type tensorRT --conf 0.6 --infer_size 640 640 --device cuda --path ./assets/dog.jpg --end2end`
Got error:
```
File "/home/xingjian/Projects/damo-yolo/damo/utils/boxes.py", line 51, in multiclass_nms
    num_classes = multi_scores.size(1)
                  │            └ <method 'size' of 'torch._C._TensorBase' objects>
                  └ tensor([100.])

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

### To Reproduce

Shown above

**Comment by jyqi** [comment]
Thanks for your attention, we have fixed this bug. Please pull the latest code and run the inference again.
