### ISSUE TITLE
Get class-wise precision & recall in the Evaluation

### ISSUE THREAD

**Issue by Nuwan1654** [tinyvision/DAMO-YOLO#84]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

Hi, I have trained the DAMO Yolo on my custom dataset with 10 classes, I need to get the class-wise precision and recall, how can I get that in the evaluation.

**Comment by jyqi** [comment]
Thanks for your attention to DAMO-YOLO. You can get class-wise precision & recall in the evaluation by following steps:
Step1. Edit PythonAPI/pycocotools/coco.py and add following code in green area.
![image](https://user-images.githubusercontent.com/1546198/223007224-f8552d53-67a6-456a-a53c-3f74aaf3f9e9.png)
Step2. Edit PythonAPI/pycocotools/cocoeval.py and add following code in green area.
![image](https://user-images.githubusercontent.com/1546198/223007273-ca024e5b-892c-4d65-8889-c9966e9e0e80.png)

**Comment by Nuwan1654** [comment]
@jyqi Thanks for these instructions, I have another question though, I started the training using the following command `python -m torch.distributed.launch --nproc_per_node=1  tools/train.py -f configs/damoyolo_tinynasL35_M.py`, then after finishing it I got 20 checkpoints, saved, how can I select the best one,, like in yolov5/7, Is there any configuration to make it save only the best wights,

**Comment by jyqi** [comment]
Currently we do not have  the feature of selecting the best checkpoint. You can find the best one by querying training logs.
