### ISSUE TITLE
Why remove identity branch in RepConv?

### ISSUE THREAD

**Issue by xingguang12** [tinyvision/DAMO-YOLO#85]
### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar feature requests.

### Description

When I saw your code carefully, I found something deifferent between your code with RepVGGBlock( https://github.com/DingXiaoH/RepVGG/blob/main/repvgg.py )
![Snipaste_2023-03-06_16-57-47](https://user-images.githubusercontent.com/57353111/223064008-22474cee-efa8-476f-96c4-7cfc745837b8.png)
![Snipaste_2023-03-06_16-56-57](https://user-images.githubusercontent.com/57353111/223064056-f5793029-741a-44bd-b9a0-a42a2b466545.png)
when  out_channels == in_channels ,  identity branch will exist,
Why remove identity branch in RepConv?  why remove this  identity branch  ?  Is this op will improve the accuracy or some how?
I want to konw this, please tell me ,thanks a lot

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xingguang12** [comment]
sorry this is a question , I choose enhancement option.
In my view , this may reduce precision

**Comment by jyqi** [comment]
Thanks for your attention to DAMO-YOLO.  By analyzing the combination and corresponding performance of RepConv and different architectures, we find that the identity connection in RepConv will destroy the residual in ResNet and the concatenation in DenseNet. In our backbone and Neck, we have many res-link and concatenation OP, therefore, we remove identity branch in RepConv, the accuracy also improves as we expect.
