### ISSUE TITLE
[Bug]: TypeError: transform_img() got an unexpected keyword argument 'keep_ratio'

### ISSUE THREAD

**Issue by wonbeomjang** [tinyvision/DAMO-YOLO#87]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

Ubuntu 20.04

### Device

AMD Ryzen 7 3700X, RTX 3090

### CUDA version

11.3

### Python version

3.8

### PyTorch version

1.10.1

### torchvision version

0.11.2

### Describe the bug

I follow the way to run demo code and met the argument error.

```bash
(DAMO-YOLO) wonbeom@wonbeom:~/Desktop/DAMO-YOLO$ python tools/demo.py -f ./configs/damoyolo_tinynasL25_S.py --engine ./damoyolo_tinynasL25_S.pth --engine_type torch --conf 0.6 --infer_size 640 640 --device cuda --path ./assets/dog.jpg
Inference with torch engine!
2023-03-07 16:04:31.287 | ERROR    | __main__:<module>:349 - An error has been caught in function '<module>', process 'MainProcess' (19034), thread 'MainThread' (140371055060800):
Traceback (most recent call last):

> File "tools/demo.py", line 349, in <module>
    main()
    └ <function main at 0x7faaabb33b80>

  File "tools/demo.py", line 313, in main
    bboxes, scores, cls_inds = infer_engine.forward(origin_img)
                               │            │       └ array([[[ 57,  58,  50],
                               │            │                 [ 58,  59,  51],
                               │            │                 [ 60,  61,  53],
                               │            │                 ...,
                               │            │                 [142,  89,  47],
                               │            │                 [ 88...
                               │            └ <function Infer.forward at 0x7faaabb339d0>
                               └ <__main__.Infer object at 0x7faaa5dcaa60>

  File "tools/demo.py", line 223, in forward
    image, ratio = self.preprocess(image)
    │              │    │          └ array([[[ 57,  58,  50],
    │              │    │                    [ 58,  59,  51],
    │              │    │                    [ 60,  61,  53],
    │              │    │                    ...,
    │              │    │                    [142,  89,  47],
    │              │    │                    [ 88...
    │              │    └ <function Infer.preprocess at 0x7faaabb338b0>
    │              └ <__main__.Infer object at 0x7faaa5dcaa60>
    └ array([[[ 57,  58,  50],
              [ 58,  59,  51],
              [ 60,  61,  53],
              ...,
              [142,  89,  47],
              [ 88...

  File "tools/demo.py", line 162, in preprocess
    img = transform_img(origin_img, 0,
          │             └ array([[[ 57,  58,  50],
          │                       [ 58,  59,  51],
          │                       [ 60,  61,  53],
          │                       ...,
          │                       [142,  89,  47],
          │                       [ 88...
          └ <function transform_img at 0x7faaabb335e0>

TypeError: transform_img() got an unexpected keyword argument 'keep_ratio'
```

### To Reproduce

python tools/demo.py -f ./configs/damoyolo_tinynasL25_S.py --engine ./damoyolo_tinynasL25_S.pth --engine_type torch --conf 0.6 --infer_size 640 640 --device cuda --path ./assets/dog.jpg

### Hyper-parameters/Configs

default config

### Screenshots

![image](https://user-images.githubusercontent.com/40621030/223349706-ac13e57f-27ed-4e0e-a53e-32775847e4cd.png)

### Additional

I made pull request in https://github.com/tinyvision/DAMO-YOLO/pull/86. If you don't mind merging, I'd appreciate it if you could merge.

**Comment by XianzheXu** [comment]
Your pull request is merged, thanks for your contribution! This issue will be closed, if you have another related issues, feel free to reopen it.
