### ISSUE TITLE
where is the damo model

### ISSUE THREAD

**Issue by pyther-hub** [tinyvision/DAMO-YOLO#88]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

I wanted to create the model and run on my system but not able to find the model structure

**Comment by linselect** [comment]
I have the same issue, during training it prompts 'No module named damo

**Comment by cwhgn** [comment]
> ### Before Asking
> * [x]  I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。
> * [x]  I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。
> * [x]  I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。
> 
> ### Search before asking
> * [x]  I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.
> 
> ### Question
> I wanted to create the model and run on my system but not able to find the model structure
> 
> ### Additional
> _No response_

We do not get your question very well. Can you provide the srceenshot of your error?

**Comment by cwhgn** [comment]
> I have the same issue, during training it prompts 'No module named damo

It may be caused by the failure of installation. You can try `export PYTHONPATH=$PWD:$PYTHONPATH`. A similar question can be found in [ISSUE #11](https://github.com/tinyvision/DAMO-YOLO/issues/11).

**Comment by pyther-hub** [comment]
sir I have to use the model for one task, I am able to find the weights of the model but not able to find the model structure and I want to do it by using python only, I tried to use the 
`from damo.detectors.detector import  build_local_model
`
but still It doesn't work

**Comment by cwhgn** [comment]
> 

Thanks for your attention. However, can you provide more details about your operations step by step or the srceenshot of your error? I can not figure out your problem from your description so far.

**Comment by cwhgn** [comment]
> sir I have to use the model for one task, I am able to find the weights of the model but not able to find the model structure and I want to do it by using python only, I tried to use the `from damo.detectors.detector import build_local_model ` but still It doesn't work

Thanks for your attention. However, I can not figure out your problem from your description so far. Can you provide more details of your operations step by step, or the srceenshot of your error?
