### ISSUE TITLE
 I think the pictures in your paper are not rigorous in several places

### ISSUE THREAD

**Issue by xingguang12** [tinyvision/DAMO-YOLO#91]
### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar feature requests.

### Description

After carefully reading the code of DAMO-YOLO, I think there are several problems with your picture.
![Snipaste_2023-03-12_20-09-14](https://user-images.githubusercontent.com/57353111/224543719-e1cd5f59-7350-490b-a622-2372fef3091e.png)
1. the number of fusion block is 5 
2. The shortcut operation on your diagram is not drawn
![Snipaste_2023-03-12_20-06-35](https://user-images.githubusercontent.com/57353111/224545939-a0eac0f6-4dcd-4a32-b195-08b17279e8fb.png)
3.There should be a 1*1 convolutional layer after the final Concat operation to adjust the number of channels
![Snipaste_2023-03-12_20-02-09](https://user-images.githubusercontent.com/57353111/224546093-434f7123-28e7-48f2-9658-a2c60a2527d6.png)
4.The representation of xN on your picture is easy to mislead others

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xingguang12** [comment]
I drew a sketch, please check if there is any problem, please help me to take a closer look.
![image](https://user-images.githubusercontent.com/57353111/224546763-6f43fa55-86ad-4b29-8ccb-78b48f469154.png)

**Comment by xingguang12** [comment]
I have another question. Why do you want to change the activation function in RepConv from ReLU to SiLU? Is there any benefit? Please tell me the details, thank you very much

**Comment by jyqi** [comment]
> I drew a sketch, please check if there is any problem, please help me to take a closer look. ![image](https://user-images.githubusercontent.com/57353111/224546763-6f43fa55-86ad-4b29-8ccb-78b48f469154.png)

Sorry for the misunderstanding caused by the figure in Our paper. The reason why we remove  node 7 is that it only accepts one input degree (i.e. node 5). we verified the accuracy of the model of 1) using Fusion Block for feature transformation and 2) directly assigned node 5 as node 7, and found that the accuracy difference is small. Therefore, in order to speed up the model time, we adopted the second scheme, but the diagram has not been updated accordingly. 

The sketch you drawn is correct and comprehensive, which provides some help on revising our figure, Thanks a lot.

**Comment by jyqi** [comment]
> I have another question. Why do you want to change the activation function in RepConv from ReLU to SiLU? Is there any benefit? Please tell me the details, thank you very much

For the activation function in RepConv, we use ReLU in the Tiny and Small models and SiLU in the Medium model. The reason why we use SiLU on the M model is that it can bring larger accuracy gain than inference speed increases in relative proportion.

**Comment by xingguang12** [comment]
> > I drew a sketch, please check if there is any problem, please help me to take a closer look. ![image](https://user-images.githubusercontent.com/57353111/224546763-6f43fa55-86ad-4b29-8ccb-78b48f469154.png)
> 
> Sorry for the misunderstanding caused by the figure in Our paper. The reason why we remove the extra node is that it only accepts one input degree. we verified the accuracy of the model of 1) using Fusion Block for feature transformation and 2) directly assigned its parent node as the extra node, and found that the accuracy difference is small. Therefore, in order to speed up the model time, we adopted the second scheme, but the diagram has not been updated accordingly.
> 
> The sketch you drawn is correct and comprehensive, which provides some help on revising our figure, Thanks a lot.


Thank you for your recognition of my work

**Comment by xingguang12** [comment]
> > I have another question. Why do you want to change the activation function in RepConv from ReLU to SiLU? Is there any benefit? Please tell me the details, thank you very much
> 
> For the activation function in RepConv, we use ReLU in the Tiny and Small models and SiLU in the Medium model. The reason why we use SiLU on the M model is that it can bring larger accuracy gain than inference speed increases in relative proportion.

thanks a lot, In a model of the same size, what is the impact on the accuracy of replacing ReLU with SiLU? (on your dataset).I'm trying to modify DAMO-YOLO recently, but I can't get a GPU on the computing platform these days and I haven't started the experiment yet. Do you have any good modification suggestions?

**Comment by jyqi** [comment]
> > > I have another question. Why do you want to change the activation function in RepConv from ReLU to SiLU? Is there any benefit? Please tell me the details, thank you very much
> > 
> > 
> > For the activation function in RepConv, we use ReLU in the Tiny and Small models and SiLU in the Medium model. The reason why we use SiLU on the M model is that it can bring larger accuracy gain than inference speed increases in relative proportion.
> 
> thanks a lot, In a model of the same size, what is the impact on the accuracy of replacing ReLU with SiLU? (on your dataset).I'm trying to modify DAMO-YOLO recently, but I can't get a GPU on the computing platform these days and I haven't started the experiment yet. Do you have any good modification suggestions?

On Medium model, replace ReLU with SiLU can achieve mAP gain of around 1.0%. 
For the DAMO-YOLO modification, 1) you can customize your own backbone by our TinyNAS(https://github.com/alibaba/lightweight-neural-architecture-search/blob/main/scripts/damo-yolo/Tutorial_NAS_for_DAMO-YOLO_cn.md), 2) use Transformer structure, 3) replace zero-head with recently advanced head, 4) use dataset auto-augmentation and so on.
