### ISSUE TITLE
No module named 'cuda'

### ISSUE THREAD

**Issue by 140ai** [tinyvision/DAMO-YOLO#92]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

No module named 'cuda'
How to install this package?please!

**Comment by HYLcool** [comment]
Hi, you might need to install `cuda-python` as below:
```
pip install cuda-python
```

**Comment by 140ai** [comment]
> Hi, you might need to install `cuda-python` as below:
> 
> ```
> pip install cuda-python
> ```

thanks
I get three class in cv_tinynas_object-detection_damoyolo_safety-helmet，what is the third class？0='safety hat', 1='no safety hat', what is the latest class?

**Comment by 140ai** [comment]
> > Hi, you might need to install `cuda-python` as below:
> > ```
> > pip install cuda-python
> > ```
> 
> thanks I get three class in cv_tinynas_object-detection_damoyolo_safety-helmet，what is the third class？0='safety hat', 1='no safety hat', what is the latest class?

safety-helmet weights has three classes

**Comment by jyqi** [comment]
> > > Hi, you might need to install `cuda-python` as below:
> > > ```
> > > pip install cuda-python
> > > ```
> > 
> > 
> > thanks I get three class in cv_tinynas_object-detection_damoyolo_safety-helmet，what is the third class？0='safety hat', 1='no safety hat', what is the latest class?
> 
> safety-helmet weights has three classes

Hello, In our Helmet Detection Model, we support only one category detection, which is 'Helmet', For more realization detail, you can check following link https://www.kaggle.com/code/yikijiang/damo-yolo-person-helmet-detection-for-begginers/notebook.
Where do you find that the model has three categories?

**Comment by 140ai** [comment]
> > > > 您好，您可能需要安装`cuda-python`如下：
> > > > ```
> > > > pip install cuda-python
> > > > ```
> > > 
> > > 
> > > thanks 我在cv_tinynas_object-detection_damoyolo_safety-helmet 得到了三级，第三级是什么？0='safety hat', 1='no safety hat',最新的级是什么？
> > 
> > 
> > 安全头盔重量分为三类
> 
> 您好，在我们的头盔检测模型中，我们只支持一种类别检测，即“头盔”，更多实现细节，您可以查看以下链接[https://www.kaggle.com/code/yikijiang/damo-yolo-person -helmet-detection-for-begginers/笔记本](https://www.kaggle.com/code/yikijiang/damo-yolo-person-helmet-detection-for-begginers/notebook)。 您在哪里发现该模型具有三个类别？

using below code.

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
model_id = 'damo/cv_tinynas_object-detection_damoyolo_safety-helmet'
input_location = 'https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/image_safetyhat.jpg'
safety_hat_detection = pipeline(Tasks.domain_specific_object_detection, model=model_id)
result = safety_hat_detection(input_location)
print("result is : ", result)

in damoyolo_tinynasL25_S_safetyhelmet.pt, the config file must set 'num_classes': 3

**Comment by jyqi** [comment]
I find that your problem is on Safety Helmet Detection, not NFL Helmet Detection. Sorry for misunderstanding your question. For safety helmet detection, the latest class '2' is '_ignore_' class for some legacy reason and you just ignore it.
