### ISSUE TITLE
Hi, tested with DAMO-N but speed not as expected

### ISSUE THREAD

**Issue by jinfagang** [tinyvision/DAMO-YOLO#94]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

I have tried with 416 416 input of DAMO-N, using MNN to run it on CPU, the speed is about 40ms overall.

this speed if out of my expectations, I thought it could be much more faster. I also tried onnxruntime, the speed is about 80ms on CPU.

My CPU is i7 same hardware tested also with yolov8, the speed is more faster.

I dont know why.

### Additional

cvsdv

**Comment by XianzheXu** [comment]
Sorry for the misleading, the latency of damo-n in float32 on intel-8163 is 35ms not 3.5ms, we have corrected it in the README. Thanks for your feedback.

**Comment by jinfagang** [comment]
@XianzheXu Oh... It should be a huge mistake, I am doubting my C++ problem and debug it for almost one night.

How does this happened to be much more slower than yolov8n?

**Comment by XianzheXu** [comment]
We sincerely apologize for our oversight and any inconvenience caused. 

The optimization level of operators by the inference engine has a significant impact on the latency evaluation of the model. For example, most inference engines have deep optimization for ordinary convolution, but the optimization for depth-wise convolution is relatively weak.

 Our damoyolo-n model, designed for edge devices, uses a large number of depth-wise convolutions, while yolov8n mainly uses ordinary convolutions. This results in damoyolo-n having significantly lower FLOPs than yolov8n, but its speed may not necessarily be faster. You may try using other inference engines for latency evaluation, which may yield different results.

**Comment by jinfagang** [comment]
@XianzheXu thanks, I have tried with MNN, the speed on same CPU still relatively slower than yolov8n, since yolov8n using 640 as input while damoyolo-n even smaller inputs, there might still a gap between them

**Comment by XianzheXu** [comment]
@jinfagang Hi, we have upgrade our DAMO-YOLO lightweight model for edge devices by replacing and upgrading some of its time-consuming modules, resulting in significant improvements in both speed and accuracy. Using OpenVINO as the inference engine on Intel CPUs, benchmark results have shown that the upgraded DAMO-YOLO  lightweight models have clear advantages over YOLOv8n. We will provide further technical details and comprehensive data in an upcoming technical report update. We cordially invite you to try out our updated model.

**Comment by jinfagang** [comment]
@XianzheXu  thank u so much, will try it.
