### ISSUE TITLE
torch转tensorrt失败

### ISSUE THREAD

**Issue by klxh21** [tinyvision/DAMO-YOLO#97]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

python converter.py -f configs/damoyolo_tinynasL20_N.py -c damoyolo_tinynasL20_N_351.pth --batch_size 1 --img_size 416  --trt
按照指导操作后失败

### Additional

![Uploading 屏幕截图 2023-03-31 101330.png…]()
![Uploading 屏幕截图 2023-03-31 101453.png…]()

**Comment by jyqi** [comment]
你好，感谢对DAMO-YOLO的关注，你这边上传的截图看不到，可否重新上传一下？

**Comment by klxh21** [comment]
&nbsp;


快乐小黑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqi ***@***.***&gt;; 
发送时间: 2023年3月31日(星期五) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tinyvision/DAMO-YOLO] torch转tensorrt失败 (Issue #97)





 
你好，感谢对DAMO-YOLO的关注，你这边上传的截图看不到，可否重新上传一下？

**Comment by klxh21** [comment]
![屏幕截图 2023-03-31 101330](https://user-images.githubusercontent.com/125724696/229040728-c5033f2c-a648-4a2d-b9be-29e7f79aa37a.png)
![屏幕截图 2023-03-31 101453](https://user-images.githubusercontent.com/125724696/229040736-94ec44b6-ad42-46ca-8a8f-8b49da74b7c5.png)

**Comment by jyqi** [comment]
你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt

**Comment by chunguangqu** [comment]
> 你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt

您好，我通过【python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval】进行模型转换会报下面的错误。我用【trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt】可以将模型转成trt格式，但是通过【python tools/trt_eval.py -f configs/damoyolo_tinynasL25_S.py -trt deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --batch_size 1 --img_size 640 --end2end】进行推理时还会报相同的错误，请问是哪里的原因呢？谢谢！
![image](https://user-images.githubusercontent.com/38381204/230778645-69683dce-934d-4d08-93d1-4fd05039cab4.png)
我的python版本为3.7
pytorch = 1.12 + cuda11.6

**Comment by jyqi** [comment]
> > 你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt
> 
> 您好，我通过【python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval】进行模型转换会报下面的错误。我用【trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt】可以将模型转成trt格式，但是通过【python tools/trt_eval.py -f configs/damoyolo_tinynasL25_S.py -trt deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --batch_size 1 --img_size 640 --end2end】进行推理时还会报相同的错误，请问是哪里的原因呢？谢谢！ ![image](https://user-images.githubusercontent.com/38381204/230778645-69683dce-934d-4d08-93d1-4fd05039cab4.png) 我的python版本为3.7 pytorch = 1.12 + cuda11.6

你好，从Converter的报错来看，模型已经成功转换得到了TRT文件，在eval模块报错。你可以核对一下转出的end2end_trt是否带有NMS模块。
另外核对一下TensorRT版本是否为7.1.2.6及以上。

**Comment by chunguangqu** [comment]
> > > 你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt
> > 
> > 
> > 您好，我通过【python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval】进行模型转换会报下面的错误。我用【trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt】可以将模型转成trt格式，但是通过【python tools/trt_eval.py -f configs/damoyolo_tinynasL25_S.py -trt deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --batch_size 1 --img_size 640 --end2end】进行推理时还会报相同的错误，请问是哪里的原因呢？谢谢！ ![image](https://user-images.githubusercontent.com/38381204/230778645-69683dce-934d-4d08-93d1-4fd05039cab4.png) 我的python版本为3.7 pytorch = 1.12 + cuda11.6
> 
> 你好，从Converter的报错来看，模型已经成功转换得到了TRT文件，在eval模块报错。你可以核对一下转出的end2end_trt是否带有NMS模块。 另外核对一下TensorRT版本是否为7.1.2.6及以上。

你好，我看到有生成转成功的onnx和trt文件。
我的tensorrt版本为8.4.2.4
怎么确认转出的end2end_trt是否带有NMS模块？

**Comment by jyqi** [comment]
> > > > 你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt
> > > 
> > > 
> > > 您好，我通过【python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval】进行模型转换会报下面的错误。我用【trtexec --onnx=damoyolo_tinynasL20_N_351.onnx **--tacticSources=-cublasLt,+cublas** --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt】可以将模型转成trt格式，但是通过【python tools/trt_eval.py -f configs/damoyolo_tinynasL25_S.py -trt deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --batch_size 1 --img_size 640 --end2end】进行推理时还会报相同的错误，请问是哪里的原因呢？谢谢！ ![image](https://user-images.githubusercontent.com/38381204/230778645-69683dce-934d-4d08-93d1-4fd05039cab4.png) 我的python版本为3.7 pytorch = 1.12 + cuda11.6
> > 
> > 
> > 你好，从Converter的报错来看，模型已经成功转换得到了TRT文件，在eval模块报错。你可以核对一下转出的end2end_trt是否带有NMS模块。 另外核对一下TensorRT版本是否为7.1.2.6及以上。
> 
> 你好，我看到有生成转成功的onnx和trt文件。 我的tensorrt版本为8.4.2.4 怎么确认转出的end2end_trt是否带有NMS模块？

可以执行trt推理，观察是否有4个输出，若有4个输出则带有NMS模块。4个输出分别为'num_dets', 'det_boxes', 'det_scores', 'det_classes'。

**Comment by klxh21** [comment]
好的感谢
&nbsp;


快乐小黑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yiqi ***@***.***&gt;; 
发送时间: 2023年4月14日(星期五) 上午10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tinyvision/DAMO-YOLO] torch转tensorrt失败 (Issue #97)





     
你好，1）onnx simplify failed的问题我这边使用开源仓没有复现，你可以在linux环境重新导出测试；2）关于trt cublas64的问题，你可以尝试命令行导出：trtexec --onnx=damoyolo_tinynasL20_N_351.onnx --tacticSources=-cublasLt,+cublas --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt
  
您好，我通过【python tools/converter.py -f configs/damoyolo_tinynasL25_S.py -c damoyolo_tinynasL25_S.pth --batch_size 1 --img_size 640 --trt --end2end --trt_eval】进行模型转换会报下面的错误。我用【trtexec --onnx=damoyolo_tinynasL20_N_351.onnx --tacticSources=-cublasLt,+cublas --workspace=2048 --fp16 --saveEngine=damoyolo_tinynasL20_N_351.trt】可以将模型转成trt格式，但是通过【python tools/trt_eval.py -f configs/damoyolo_tinynasL25_S.py -trt deploy/damoyolo_tinynasL25_S_end2end_fp16_bs1.trt --batch_size 1 --img_size 640 --end2end】进行推理时还会报相同的错误，请问是哪里的原因呢？谢谢！  我的python版本为3.7 pytorch = 1.12 + cuda11.6
  
你好，从Converter的报错来看，模型已经成功转换得到了TRT文件，在eval模块报错。你可以核对一下转出的end2end_trt是否带有NMS模块。 另外核对一下TensorRT版本是否为7.1.2.6及以上。
  
你好，我看到有生成转成功的onnx和trt文件。 我的tensorrt版本为8.4.2.4 怎么确认转出的end2end_trt是否带有NMS模块？
  
可以执行trt推理，观察是否有4个输出，若有4个输出则带有NMS模块。4个输出分别为'num_dets', 'det_boxes', 'det_scores', 'det_classes'。
