### ISSUE TITLE
Nanos models onnx exportation inconsistent with previous model

### ISSUE THREAD

**Issue by lucasjinreal** [tinyvision/DAMO-YOLO#99]
### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar feature requests.

### Description

Previous model have outputs concatenated, but new one separated a lot. 

This is not a problem, but caused very serious inconsistency for deploy code which **could be same without even change a line to deploy all DAMO series models**

Old:

![image](https://user-images.githubusercontent.com/21303438/231945535-1385542c-fee4-4a88-a3f1-5aad03216aa7.png)

New:

![image](https://user-images.githubusercontent.com/21303438/231945550-3972191f-9a1c-4517-99a2-53ff7f89aa4e.png)

Can we just merge them all **exactly same as previous and same like yolov5/yolov7/yolov8 so that  deploy code can compatible at maximum?**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jinfagang** [comment]
Also, I even doubt the new nanos models are wrong, since I can not really figure out where is box....

**Comment by XianzheXu** [comment]
Hi, the new model's is exported with --benchmark,  which means the post-processing is ignored.  You can export onnx model without --benchmark to keep consistency with your deploy codes.  

In the onnx output, tensor shaped as [1, 32, 52, 52], [1, 32, 26, 26], [1, 32, 13, 13] is the box before post-process.

**Comment by XianzheXu** [comment]
In order to provide convenience for developers and maintain consistency with our previous code, we have updated the ONNX download link. You can now download the ONNX model that includes post-processing.

**Comment by jinfagang** [comment]
@XianzheXu thank u so much!

**Comment by jinfagang** [comment]
@XianzheXu hi, I downloaded damoyolo_nano_small.onnx, it still same.

**Comment by XianzheXu** [comment]
> @XianzheXu hi, I downloaded damoyolo_nano_small.onnx, it still same.

Please retry it, the download link is updated now.
